apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "shohebpathan12344@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "uubj uixd lmqv tftm"
type: Opaque

# Passw0rd@1234